apiVersion: v1
kind: PersistentVolumeClaim
metadata: 
  name: efs-dynamic
spec:
  storageClassName: roboshop-efs
  resources:
    requests:
      storage: 5Gi
  accessModes:
  - ReadWriteMany
---
apiVersion: v1
kind: Pod
metadata: 
  name: nginx
  labels:
    purpose: efs-dynamic
spec:
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: nginx-html
      mountPath: /usr/share/nginx/html
  volumes:
  - name: nginx-html
    persistentVolumeClaim:
      claimName: efs-dynamic
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-efs-static
spec:
  type: LoadBalancer
  selector:
    purpose: efs-static
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30007  # ephemeral 30000 - 32767