apiVersion: v1
kind: Pod
metadata:
  name: annotations-demo
  annotations:
    jenkins.url: "http://jenkins.devops.com/build/job"
    imageregistry: "http://hub.docker.com/"
spec:
  containers:
  - name: nginx
    image: nginx 