apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    app: nginx
    purpose: satefulset-nginx
spec:
  #type: LoadBalancer for DB statefulset not required explicitly
  selector:
    app: nginx
    purpose: satefulset-nginx
  ports:
  - port: 80
    name: www
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-headless
  labels:
    app: nginx
    purpose: satefulset-nginx
spec:
  clusterIP: None
  selector:
    app: nginx
    purpose: satefulset-nginx
  ports:
  - port: 80
    name: www
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ss-nginx
  labels:
    app: nginx
    purpose: satefulset-nginx
spec:
  serviceName: "nginx-headless"  # for peer discovery we need to give it will fetch member machines in the cluster
  replics: 3
  selector:
    matchLabels:
      app: nginx
      purpose: satefulset-nginx
  template:
    metadata:
      labels:
        app: nginx
        purpose: satefulset-nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
          name: web
        volumeMounts:
        - name: www
          mountPath: /usr/share/nginx/html
      vomumeClaimTemplates:
      - metadata:
          name: www 
        spec:
          accessModes: [ "ReadWriteOnce" ]
          storgeClassName: "roboshop-ebs" # using storage class which is already available 
        resources:
          requests:
            storage: 1Gi
